language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(ls target/rpm/graylog2-plugin-output-riemann/RPMS/noarch/graylog2-plugin-output-riemann-*.rpm)
  - export RELEASE_PKG_FILE=$(ls target/graylog2-plugin-output-riemann-*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "0/yehEDS7ea4j56cib3vZPfRfR4PBH8ASoDQxU3YJJu2oybxStKP3T8ODK8gfZVtGurdgjQ6D0NVmuoiA0gmaQ2sxR7spNOhzFV5XaSjgorMJ5a/hN0bfznVt6QHzKUvaumlp9q/tcJOzJdKybpBVnrgOxE57sAZZ+QUBIWA0Q4="
  file: 
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7
